services:
  api:
    build:
      context: ".."
      dockerfile: "docker/backend.Dockerfile"
    container_name: rfc-api
    ports:
      - "5001:5000"
    restart: unless-stopped

  web:
    build:
      context: ".."
      dockerfile: "docker/frontend.Dockerfile"
    container_name: rfc-web-ui
    depends_on:
      - api
    ports:
      - "8091:80"
    restart: unless-stopped
